path: C:\CAROLINA\AI_BOOTCAMP\P16_VPC\computer_vision_G2\data
train: C:\CAROLINA\AI_BOOTCAMP\P16_VPC\computer_vision_G2\data\train\images
val: C:\CAROLINA\AI_BOOTCAMP\P16_VPC\computer_vision_G2\data\valid\images
test: C:\CAROLINA\AI_BOOTCAMP\P16_VPC\computer_vision_G2\data\test\images
names:
  0: nike_logo
nc: 1
